[package]
name = "shoehorn_circle"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]

[dependencies]

card_deck="*"
lazyf="*"
rand = "*"
enum_derive="*"
#custom_derive="*"
macro-attr="*"
itertools="*"
bracket_parse={path="../../mlibs/bracket_parse/"}
